# Generated by Django 5.1.1 on 2024-09-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notion_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notiontoken',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='notiontoken',
            name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='notiontoken',
            name='token_type',
        ),
        migrations.AddField(
            model_name='notiontoken',
            name='bot_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notiontoken',
            name='workspace_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='notiontoken',
            name='access_token',
            field=models.CharField(default='', max_length=255),
        ),
    ]
