# Generated by Django 5.1.1 on 2024-09-14 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notion_api', '0002_remove_notiontoken_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notiontoken',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='notiontoken',
            name='workspace_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
