# Generated by Django 5.0.4 on 2024-09-14 06:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notion_api', '0003_notiontoken_name_notiontoken_workspace_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotionPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notion_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.JSONField()),
                ('vector', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('cluster', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
