# Generated by Django 5.0.4 on 2024-09-14 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notion_api', '0004_notionpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notiontoken',
            name='created_at',
        ),
    ]
