# Generated by Django 5.0.4 on 2024-09-14 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notion_api', '0005_remove_notiontoken_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notiontoken',
            name='user',
        ),
    ]
