# Generated by Django 5.0.4 on 2024-09-16 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notion_api', '0008_alter_notiontoken_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notiontoken',
            name='user',
        ),
    ]
