# Generated by Django 5.0.4 on 2024-09-19 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notion_api', '0009_remove_notiontoken_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notiontoken',
            name='user',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
